/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ukmjnhvivrzdtvkhftpq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrbWpuaHZpdnJ6ZHR2a2hmdHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMjkxNDEsImV4cCI6MjA3NjcwNTE0MX0.P83-7kG64xFTmS-dbEeCXjJfXAg_rB4y_J8TLXqJ2I4"